# Generated by Django 4.0.3 on 2022-04-27 18:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tshirt', '0005_alter_tshirt_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tshirt',
            name='position',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), null=True, size=2),
        ),
    ]
