version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: dbpostgresql
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    volumes:
      - pgdata:/var/lib/posgresql/data
  vendingmachine:
    build:
      context: .
    entrypoint: /run_migrations.sh
    ports:
      - "8000:8000"
    volumes:
      - ./:/vendingmachine/src
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
volumes:
  pgdata: