# Generated by Django 4.0.3 on 2022-04-03 20:04

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('measure', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0), size=3)),
            ],
        ),
        migrations.CreateModel(
            name='Tshirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, max_length=100)),
                ('color', models.CharField(max_length=30)),
                ('price', models.FloatField(default=0.0)),
                ('qtyInStock', models.IntegerField(default=1)),
                ('photo', models.ImageField(blank=True, upload_to='statics/tshirts/')),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Unisex')])),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tshirt.size')),
            ],
        ),
    ]
