# Generated by Django 4.0.3 on 2022-04-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tshirt', '0003_alter_tshirt_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshirt',
            name='photo',
            field=models.ImageField(null=True, upload_to='static/img/tshirts/'),
        ),
    ]
