# Generated by Django 4.0.3 on 2022-03-30 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Camiseta',
            new_name='Task',
        ),
    ]
